### ISSUE TITLE
Chinese misspelled and uncapitalized

### ISSUE THREAD

**Issue by graybeal** [ontoportal/website#10]
Got feedback that Chinese is on the about page as chineese, once in the text and once in the image. Also that 'chineese' and 'french' should be capitablized.

**Comment by graybeal** [comment]
I was able to patch the image through directly copying and moving part of the image, and I just edited the text directly. I pushed these changes on the theory they were small enough to not require review.  Verified all looks good on the site.  https://github.com/ontoportal/website/commit/cf9c8fdf94f17b7818d29abf7bd21cb17843c318 

But we should change the capitalization of the languages in the image, if we want to be appropriately English-formal. I don't have the original image, so it would be hard to do that in Preview. @syphax-bouazzouni ?

**Comment by syphax-bouazzouni** [comment]
Hi @graybeal , thanks for the fix.

> But we should change the capitalization of the languages in the image if we want to be appropriately English-formal. I don't have the original image, so it would be hard to do that in Preview. @syphax-bouazzouni ?

@jonquet is the one having the original image file. (_graph original made by Xeni from Ecoportal for the [ontoportal workshop 2022 report](https://docs.google.com/document/d/1Q6C1FHDHD3yf7hrKY63IjVfbodumSmP4f3xO7sz-DXs/edit#)_)

**Comment by syphax-bouazzouni** [comment]
I also think, that on the [About page](https://ontoportal.org/about/), we have a duplication of information with the  two diagrams.

This one 
![image](https://github.com/ontoportal/website/assets/29259906/5b5e4cae-4720-4090-a226-6dd80725a8e2)

With this one 

![image](https://github.com/ontoportal/website/assets/29259906/1d3d3ebe-90a3-448c-95d2-c2841d4b4de5)


We should remove one of them, I think. @jonquet what is your opinion about this?

**Comment by graybeal** [comment]
This is true, but the information is slightly different, and the organization is very different, as is the availability of the subimages for use elsewhere. I'm OK with it for now.

**Comment by graybeal** [comment]
Oooh, changed my mind. The exact same content as the second screenshot is on the home page. Redundancy not good. (I wonder if it was accidentally left on the about page.)

I'd say remove it from the about page.

**Comment by jonquet** [comment]
They does not necessarily serve the same goal as the image is something to copy/paste in presentation (source file is in our GDrive) and the section listing the instances is text and logo editable by everyone (to add their stuff). 
Its true someone can make an image of the 2nd section (as done in the issue here) but still the image is a bit better for communication. 

I will remove the 2nd section form the About page and leave it on the Product page.

**Comment by jonquet** [comment]
Fixed with 3 last commits: 
https://github.com/ontoportal/website/commits/main
